services:
  - type: web
    name: fs-pokedex-web
    runtime: node
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    startCommand: npm run start-prod
    healthCheckPath: /health
